services:
  authdb:
    image: postgres:15
    container_name: authdb
    environment:
      POSTGRES_USER: juareca
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - authdb_data:/var/lib/postgresql/data
    restart: unless-stopped

  devicesdb:
    image: postgres:15
    container_name: devicesdb
    environment:
      POSTGRES_USER: juareca
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: devicesdb
    ports:
      - "5434:5432"
    volumes:
      - devicesdb_data:/var/lib/postgresql/data
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  authdb_data:
  devicesdb_data: